name: resolve-dev

channels:
  - conda-forge
  - gurobi

dependencies:
  - awscli=2.27.55
  - graphviz=8.1.0
  - gurobi>=12.0
  - kubernetes=1.24.3
  - pip=26.0.1
  - python>=3.11,<3.12
  - setuptools=66.1.1
  - coincbc

  - pip:
      # Install current repo as editable package
      - -e ".[kit,dev,jupyter,ui]"

