name: kit-dev

channels:
  - conda-forge
  - gurobi

dependencies:
  - graphviz=8.1.0
  - gurobi=10.0.2
  - python>=3.9,<3.11
  - pip=22.3.1
  - setuptools=66.1.1

  - pip:
      # Install current repo as editable package
      - -e ".[dev,ui]"
