name: kit

channels:
  - conda-forge
  - gurobi

dependencies:
  - awscli=2.15.9
  - gurobi=11.0.0
  - kubernetes=1.24.3
  - pip=22.3.1
  - python>=3.9,<3.11
  - setuptools=66.1.1

  - pip:
      # Install current repo as editable package
      - -e ".[ui]"
