name: resolve-rtd

channels:
  - conda-forge
  - gurobi

dependencies:
  - python==3.10
  - gurobi=10.0.2
  - highs=1.5.3
  - pip
  - setuptools

  - pip:
      # Install current repo as editable package
      - -e ".[ui,dev]"