name: semantic-pull-request

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review
      - review_requested
    branches:
      # Only run on PRs merging into `main`
      - main

permissions:
  pull-requests: read

jobs:
  semantic-pull-request:
    # Only run if a non-draft PR
    if: github.event.pull_request.draft == false
    name: Validate Conventional Pull Request Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
