name: Run Resolve test case

on:
  workflow_call:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'pyproject.toml'

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    container: continuumio/miniconda3
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install OS dependencies (apt-get)
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends gcc python3-dev

      - name: Create NMT environment (Miniconda)
        run: |
          conda env create -q -f environment-rtd.yml
          conda update -q -y -n nmt --all

      - name: Install pytest (Miniconda)
        run: |
          conda run -n nmt --no-capture-output conda install -q pytest

      - name: Run pytest
        run: |
          conda run -n nmt --no-capture-output --cwd tests/resolve/ pytest test_run_opt.py
